# Generated by Django 5.0.1 on 2024-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('PatientImg', models.ImageField(default='a.png', upload_to='uploads')),
                ('PatientName', models.CharField(max_length=40)),
                ('PatientMail', models.EmailField(max_length=40, unique=True)),
                ('PatientPh', models.CharField(max_length=30)),
                ('PatientDob', models.DateField()),
                ('PatientAddr', models.CharField(max_length=100)),
                ('PatientPwd', models.CharField(max_length=30)),
            ],
        ),
    ]
