# Generated by Django 5.0.1 on 2024-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientImg',
            field=models.ImageField(default='patients/a.png', upload_to='patients/uploads'),
        ),
    ]
