# Generated by Django 5.0.1 on 2024-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_patientimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartImg', models.ImageField(upload_to='uploads')),
                ('DepartName', models.CharField(max_length=50)),
            ],
        ),
    ]
