# Generated by Django 5.0.1 on 2024-02-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_patientmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorImg', models.ImageField(default='a.png', upload_to='uploads')),
                ('DoctorName', models.CharField(max_length=50)),
                ('DoctorMail', models.EmailField(max_length=50)),
                ('DoctorPwd', models.CharField(max_length=50)),
                ('DoctorPh', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.department')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
