# Generated by Django 5.0.1 on 2024-02-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_doctor_doctormail_alter_patient_patientmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('HistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor', models.CharField(max_length=30)),
                ('Patient', models.CharField(max_length=30)),
                ('AppointDate', models.DateField(default='')),
                ('AppointStartTime', models.TimeField()),
                ('AppointEndTime', models.TimeField()),
                ('Token', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AppointDate', models.DateField()),
                ('AppointStartTime', models.TimeField()),
                ('AppointEndTime', models.TimeField()),
                ('Token', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=10)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('ScheduleDate', models.DateField(blank=True, null=True)),
                ('ScheduleStartTime', models.TimeField()),
                ('ScheduleEndTime', models.TimeField()),
                ('MaxPatient', models.PositiveIntegerField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
            ],
        ),
    ]
