# Generated by Django 5.0.1 on 2024-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_history_appointment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorPh',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientPh',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
