# Generated by Django 5.0.1 on 2024-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_doctor_doctorph_alter_patient_patientph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorMail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='DoctorPh',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientMail',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientPh',
            field=models.CharField(max_length=30),
        ),
    ]
